// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOntDPXkYoV0Ku6lMlfK85ns6sKP1QNoY',
    appId: '1:369551606717:web:415bfd063c2e81a54a08d4',
    messagingSenderId: '369551606717',
    projectId: 'one-for-all-vcr',
    authDomain: 'one-for-all-vcr.firebaseapp.com',
    storageBucket: 'one-for-all-vcr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1HCWfopqBGMgIQlrF9SpAdO8ADwOByd4',
    appId: '1:369551606717:android:104dc284da64b5524a08d4',
    messagingSenderId: '369551606717',
    projectId: 'one-for-all-vcr',
    storageBucket: 'one-for-all-vcr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFbW0TTdb6WFwQ1DOUzUxN1RM8LDlWLq0',
    appId: '1:369551606717:ios:ef7906ce06efb7144a08d4',
    messagingSenderId: '369551606717',
    projectId: 'one-for-all-vcr',
    storageBucket: 'one-for-all-vcr.appspot.com',
    iosClientId: '369551606717-bn1o8v0i10lcfcltt1qgp5elsotftd70.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneforall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFbW0TTdb6WFwQ1DOUzUxN1RM8LDlWLq0',
    appId: '1:369551606717:ios:f636d0290a5d89454a08d4',
    messagingSenderId: '369551606717',
    projectId: 'one-for-all-vcr',
    storageBucket: 'one-for-all-vcr.appspot.com',
    iosClientId: '369551606717-u206kogc67okup3ca1goehh3f9b3a624.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneforall.RunnerTests',
  );
}
